### PR TITLE
Add ability to specify versions.

### PR DESCRIPTION
**Pull request by socketwench**
This works on Debian/Ubuntu, but it may need to be broken out to multiple tasks for RHEL.

### CODE REVIEW

**Comment by geerlingguy** [comment]
Looks like it works okay with RHEL too?

**Comment by geerlingguy** [comment]
Oh... I forgot I've never successfully broken this project's tests into multi-platform containers :(

**Comment by geerlingguy** [comment]
I'll have to run a test on CentOS 7 and see what happens.

**Comment by geerlingguy** [comment]
See related: #83

**Comment by geerlingguy** [comment]
Testing on RHEL 7 now. First with no version specified, then with a version.

**Comment by geerlingguy** [comment]
Moved the commit into new PR https://github.com/geerlingguy/ansible-role-gitlab/pull/84, where I rebased (so it will run all the tests added in #83 ), and updated the new tasks to work with CentOS/RedHat as well. Thanks!

**Comment by geerlingguy** [comment]
@socketwench - Thanks again! This is merged and very slightly different, in tag 2.4.0.

**Comment by socketwench** [comment]
Yay!

**Pull request closed without merging**
