### PR TITLE
Increase gitlab installation timeout

### PR DESCRIPTION
**Pull request by AdamGoldsmith**
Addresses issue: https://github.com/geerlingguy/ansible-role-gitlab/issues/199

### CODE REVIEW

**Comment by artybdrlt** [comment]
That's exactly what we need!

**Review by BrutalBirdie — APPROVED** [review]

**Comment by BrutalBirdie** [comment]
Link to issue #199

**Comment by AdamGoldsmith** [comment]
Am I required to do anything else to get this merged, or is this just waiting for the right sign-off?

**Comment by AdamGoldsmith** [comment]
I submitted this PR almost 5 months ago. I'd really like to see these changes merged please. Is there anything else I need to do before they're merged? Thanks.

**Comment by BrutalBirdie** [comment]
@AdamGoldsmith 
Maybe you want to take a look here:

https://youtu.be/MXxPsWjMW1A

Jeff is currently sick and does not have a lot of time.

Get better soon Jeff <3

**Comment by AdamGoldsmith** [comment]
Hi @BrutalBirdie 
Thanks for your message. Please know that I have already seen Jeff's video that you linked above - he's a fantastic man and has helped thousands of people with his amazing contributions to Ansible and the greater tech community. I wish him well and quick recovery. I didn't want to come across unsentimental with my request, I am just trying to understand if there are other people who are able to merge this request, or if I was missing any information to get this done as this is my first Pull Request and it has been a while since I submitted it.

Once again, I wish Jeff well.

**Comment by NormanJS** [comment]
This is still an issue, I would love for this PR to be merged so I don't have to fork it to edit the timeout.

The timeout is hardly enough for how much an installation takes

**Pull request closed without merging**
