### PR TITLE
Added support to multiple LDAP server and params

### PR DESCRIPTION
**Pull request by mprenditore**
I've added the possibility to specify multiple LDAP servers and all the possible parameters that can be specified for the service.

I hope you'll find it useful as I do.

Thank you for putting the bases for this role!

### CODE REVIEW

**Comment by mprenditore** [comment]
up?

**Comment by mprenditore** [comment]
up

**Comment by elcomtik** [comment]
I would appreciate if this PR is merged.

@mprenditore could you please fix conflicts?

**Comment by elcomtik** [comment]
@mprenditore  could you please fix conflicts?

**Comment by elcomtik** [comment]
ping

**Comment by elcomtik** [comment]
thanks @mprenditore, still it is waiting for @geerlingguy attention

**Comment by ltsavar** [comment]
Yes please merge this feature!

**Comment by ltsavar** [comment]
would still be a good idea.....

**Comment by elcomtik** [comment]
ping

**Comment by ltsavar** [comment]
ping

**Comment by ltsavar** [comment]
ping

**Comment by ltsavar** [comment]
bla

**Comment by BrutalBirdie** [comment]
@geerlingguy this is still very useful.
Can we get a merge?

**Comment by BrutalBirdie** [comment]
The `encryption` parameter is missing for configurable option.

```yaml
encryption: 'plain' # "start_tls" or "simple_tls" or "plain"
```

**Comment by RipJitter** [comment]
I have a need for the admin_group. Looks like the [EE only](https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/files/gitlab-config-template/gitlab.rb.template#L501) variables are still not included with this.

**Comment by BrutalBirdie** [comment]
> I have a need for the admin_group. Looks like the [EE only](https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/files/gitlab-config-template/gitlab.rb.template#L501) variables are still not included with this.

You can always add these via the `gitlab_extra_settings` but I agree this can be included.
This PR is stale.
I standalone forked this role, and will add your suggestion now @RipJitter 
https://github.com/GzEvD/ansible-role-gitlab

**Comment by ltsavar** [comment]
sad

**Comment by geerlingguy** [comment]
I'll keep it open, but I'm wondering if it might just be better to break the backwards compatibility and make the PR simpler—this seems to add a lot of extra lines to support the use case of someone not updating their code to work with multiple LDAP servers.

It's not a feature I use, but I can see how some people with larger GitLab instances would like it, so I'd be amenable to merging something.

**Comment by sonofthechief** [comment]
I had the same situation and solved it by using the `gitlab_extra_settings`. Posting it here, maybe it helps someone. Took some time for me to figure out the formatting etc.

If you add the LDAP config with the extra settings, you have to remove the standard `gitlab_ldap_enabled` parameter from your vars, else the role will add empty LDAP parameters to the config, in addition to the parameters which are defined in the extra settings. 

Anyways, these are my `gitlab_extra_settings` for an LDAP server, you can check all the possible params [here](https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/files/gitlab-config-template/gitlab.rb.template). 

```
gitlab_extra_settings:
  - gitlab_rails:
# make sure to give booleans the plain type and put them in quotes, else they will be capitalized and GitLab will fail to start. This replaces gitlab_ldap_enabled.
      - key: "ldap_enabled"
        type: "plain"
        value: "true"
      - key: "ldap_servers"
        type: "plain"
        value: |
          {
          'main' => {
            'label' => 'LDAP_Display_Name',
            'host' =>  'LDAP_URL',
            'port' => 636,
            'uid' => 'cn',
            'encryption' => 'simple_tls',
            'verify_certificates' => false,
            'bind_dn' => 'CN=whatever,OU=you,OU=need',
            'password' => password',
            'active_directory' => true,
            'base' => 'DC=based,DC=base',
# admin_group and group_base only work for GitLab-EE
            'admin_group' => 'udspzzzp01_gitlab_admin',
            'group_base' => 'OU=tenants,DC=msad,DC=udsp,DC=ch',
            'attributes' => {
              'name' => 'DisplayName'
            }
            }
          }
```

**Comment by Aethylred** [comment]
Double bump for this one from me, the LDAP config as specified originally doesn't work properly in version 13.x onward due to the LDAP config becoming a multi-server hash.

**Comment by Aethylred** [comment]
@geerlingguy 
> I'll keep it open, but I'm wondering if it might just be better to break the backwards compatibility and make the PR simpler

The `gitlab.rb` config file _changes_ between major versions, and the LDAP config format is currently only suitable for version 11.x (mayby 12.x) and unsuitable for GitLab 13.x onward, most recent version is 15.x

I think the only way to resolve this _and_ maintain backwards compatibility is to either have a branch for each GitLab major release (ew) or to do multi-config with a template config for each major version. I think fragments could be reused with includes too.

**Pull request closed without merging**
