### PR TITLE
fix for #139: ansible-lint 602

### PR DESCRIPTION
**Pull request by bbaassssiiee**
When I installed this role and ran ansible-lint 4.1.0 on the playbook I got 1 error.
The solution presented by the rule however caused a deprecation warning on conditional bare variables. Using the bool filter fixes the error in a way that molecule passes without warning and ansible-lint 4.1.0 also.

Please merge for consumer integration to pass.

### CODE REVIEW

**Comment by geerlingguy** [comment]
I ignore rule 602 (see https://github.com/geerlingguy/ansible-role-gitlab/blob/master/.ansible-lint) because I hate rule 602 (see https://github.com/ansible/ansible-lint/issues/457).

**Comment by bbaassssiiee** [comment]
https://github.com/ansible/ansible-lint/issues/457#issuecomment-573091320

**Comment by geerlingguy** [comment]
@bbaassssiiee - If that is fixed finally (I haven't yet confirmed it but hopefully it is), then the best way for this would be to use the Pythonic way:

```
when: gitlab_version
```

**Comment by geerlingguy** [comment]
Nevermind, that throws the CONDITIONAL_BARE_VARS warning as you mention (silly me)—so your fix is good, but please also remove the `.ansible-lint` file from the root dir of this repo to make sure we're not skipping that rule 602 lint anymore.

**Comment by geerlingguy** [comment]
Thanks! Added one follow-up commit after identifying a more proper way to make sure it's checked as a string (since bool only works for true/false-ish strings like 0/1, or yes/no, true/false).

**Comment by bbaassssiiee** [comment]
Please release this... 
```
git checkout master
git pull
git tag 2.5.3
git push --tags
```

**Pull request merged**
