### PR TITLE
Add Nginx Listen Port and HTTPS

### PR DESCRIPTION
**Pull request by olo-dw**
In order to supporting proxied SSL, I propose to add these two parameters into the *gitlab.yml*: 
```
nginx['listen_port'] = 80
nginx['listen_https'] = false
```

See official documentation :
https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/doc/settings/nginx.md#supporting-proxied-ssl

~~Note: I added the PR #30 in order to avoid the issue #29 .~~

### CODE REVIEW

**Comment by olo-dw** [comment]
I did rebase against the new master without the /password/new commit 4aeaec0.

**Comment by geerlingguy** [comment]
Oops! Now there's a merge conflict :P

**Comment by olo-dw** [comment]
I fixed the conflict.

**Comment by geerlingguy** [comment]
Merged the other conflict, can you fix one more time? Sorry about the noise.

**Comment by olo-dw** [comment]
No problem. Thanks for your patience, I had to think about it.
I merged this new conflict.

**Pull request merged**
