### PR TITLE
#133 Add fiture for customization gitlab.rb config

### PR DESCRIPTION
**Pull request by iphizic**
We use gitlab in owr intranet with mail relay without autentification. In this case, mail notification work only unused option smtp_authentication. In this fix loop that uses only vars in list smtp settungs.
Proof: https://docs.gitlab.com/omnibus/settings/smtp.html#microsoft-exchange-no-authentication

### CODE REVIEW

**Comment by iphizic** [comment]
Tomorow im' add compatible with old smtp format

**Comment by iphizic** [comment]
Compatible added

**Comment by iphizic** [comment]
Hello, @geerlingguy can you merge?

**Comment by iphizic** [comment]
My company need thith fixes.

**Comment by geerlingguy** [comment]
There are a lot of changes in this PR, and the main change changes the entire structure of the email-related settings, without any backwards compatibility. It seems like a lot of changes that may or may not be necessary (there might be other ways to achieve what you're looking to do).

**Comment by geerlingguy** [comment]
Note that if you need this level of customization in the `gitlab.rb` file, it is probably best to override the `gitlab_config_template: "gitlab.rb.j2"` variable and use your own template with your own settings. It is more maintainable that way as well.

**Pull request closed without merging**
